@host=http://localhost:5046

GET {{host}}/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5N2QwZTZjYy0zYTRjLTQzNjEtOTFiZS0wNTc0OWY3NmExYzIiLCJnaXZlbl9uYW1lIjoiTW9oYW1lZCIsImZhbWlseV9uYW1lIjoiT3Vlc2xhdGkiLCJqdGkiOiJlMThkNmYzYy02NGFlLTQzZWItYTk0Ny1hYjJiM2NkM2EzMzQiLCJleHAiOjE2OTI0NDM1ODUsImlzcyI6IkNvZGVyTmV3cyIsImF1ZCI6IkNvZGVyTmV3cyJ9.d6O2akEcslKpGlICe-W3TTFsdaIUghtAoDrKQrwL1UM